<?php

namespace App\Models;

use App\Scopes\DeletedAtScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Ramsey\Uuid\Uuid;

class Webhook extends Model
{
    const WEBHOOK_ACTIVE = 1;
    const WEBHOOK_NOT_ACTIVE = 0;

    use HasFactory, SoftDeletes;

    protected $fillable = [
        'webhook_code',
        'name',
        'url',
        'is_active'
    ];

    protected $dates = [
        'deleted_at',
        'created_at',
        'updated_at'
    ];

    protected $with = [
        'applications'
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        Webhook::creating(function (Webhook $webhook) {
            $webhook->webhook_code = Uuid::uuid4();
        });
    }

    protected static function booted()
    {
        static::addGlobalScope(new DeletedAtScope());
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', 1);
    }

    public function applications()
    {
        return $this->hasMany(WebhookApplication::class, 'webhook_id', 'id');
    }
}
